### ISSUE TITLE
Flutter SDK version to run the example

### ISSUE THREAD

**Issue by DieTime** [alesdi/qr_code_vision#5] opened 2022-11-04 23:02 UTC
Hi, I want to say that according to the description, this is a very cool project, but I was unable to run the example on my device. I would like to know what version of Flutter SDK you are using.

**Comment by DieTime** [comment] 2022-11-04 23:04
The problems are related to the fact that Android devices can return a camera frame in YUV format.

**Comment by alesdi** [comment] 2022-11-10 00:09
Thank you for reporting the problem! I personally tested the example only on iOS. I replicated the issue on a Samsung Galaxy A32 5G running Android 12. Indeed, it seems to be related to the CameraImage decoding. Currently only bgra8888 seems to be handled correctly. It should be relatively easy to implement yuv420 decoding, manually if necessary.

**Comment by alesdi** [comment] 2023-10-12 16:56
Duplicate of #8

**Closed by alesdi** 2023-10-12 16:56 UTC
